// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHEE8loJgdk5f2dtAZGcSWxwB3CTCkE1o',
    appId: '1:556942443830:web:420780f2e9ea8e3ed1df97',
    messagingSenderId: '556942443830',
    projectId: 'serve-2998c',
    authDomain: 'serve-2998c.firebaseapp.com',
    storageBucket: 'serve-2998c.firebasestorage.app',
    measurementId: 'G-LEELKRZ64G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCufI545bOFaK0fR_wwsQYvHeBD6cdWw',
    appId: '1:556942443830:android:ad057873379d8abbd1df97',
    messagingSenderId: '556942443830',
    projectId: 'serve-2998c',
    storageBucket: 'serve-2998c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGpRHAtZrOp-NQck-nL36MtmSUhg5tQI',
    appId: '1:556942443830:ios:b9075f78f187e60ed1df97',
    messagingSenderId: '556942443830',
    projectId: 'serve-2998c',
    storageBucket: 'serve-2998c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsGpRHAtZrOp-NQck-nL36MtmSUhg5tQI',
    appId: '1:556942443830:ios:b9075f78f187e60ed1df97',
    messagingSenderId: '556942443830',
    projectId: 'serve-2998c',
    storageBucket: 'serve-2998c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHEE8loJgdk5f2dtAZGcSWxwB3CTCkE1o',
    appId: '1:556942443830:web:bff7fdd276cd3bc0d1df97',
    messagingSenderId: '556942443830',
    projectId: 'serve-2998c',
    authDomain: 'serve-2998c.firebaseapp.com',
    storageBucket: 'serve-2998c.firebasestorage.app',
    measurementId: 'G-5Y14FS24BV',
  );

}