services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: cro/serve-back:latest

  integrations:
    build:
      context: ./integrations-service
      dockerfile: Dockerfile
    image: cro/serve-integrations:latest

  front:
    build:
      context: ./app        
      dockerfile: web/Dockerfile 
    image: cro/serve-front:latest

  ai:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    image: cro/serve-ai:latest
