services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: cro/serve-back:latest

  integrations:
    build:
      context: ./integrations-service
      dockerfile: Dockerfile
    image: cro/serve-integrations:latest
