"""reintroduced image: bool into the database

Revision ID: 79d833f1c51f
Revises: a5c93ebf9e34
Create Date: 2026-03-24 20:18:24.433781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d833f1c51f'
down_revision: Union[str, Sequence[str], None] = 'a5c93ebf9e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('image', sa.Boolean(), nullable=True))
    op.add_column('communities', sa.Column('image', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('image', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('image', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    op.drop_column('posts', 'image')
    op.drop_column('communities', 'image')
    op.drop_column('businesses', 'image')
    # ### end Alembic commands ###
