"""removed image urls from postgres

Revision ID: a5c93ebf9e34
Revises: e0446b9e60d9
Create Date: 2026-03-24 13:36:24.924833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c93ebf9e34'
down_revision: Union[str, Sequence[str], None] = 'e0446b9e60d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'avatar')
    op.drop_column('communities', 'avatar')
    op.drop_column('posts', 'image')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('communities', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
