"""firebase device token added

Revision ID: c519bf6e7e88
Revises: 79d833f1c51f
Create Date: 2026-03-29 23:21:08.692584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c519bf6e7e88'
down_revision: Union[str, Sequence[str], None] = '79d833f1c51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('fcm_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('businesses', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('communities', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('communities', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('businesses', 'image',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('device_tokens')
    # ### end Alembic commands ###
