"""added images urls

Revision ID: e0446b9e60d9
Revises: ccfb10350c8b
Create Date: 2026-03-24 02:37:33.759918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0446b9e60d9'
down_revision: Union[str, Sequence[str], None] = 'ccfb10350c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('communities', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('posts', 'image')
    op.drop_column('communities', 'avatar')
    op.drop_column('businesses', 'avatar')
    # ### end Alembic commands ###
